import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteNav,SiteFooter} from '../../components/SiteChrome';
import BookingForm from '../../components/BookingForm';
import InquiryForm from '../../components/InquiryForm';

const basketball=[['Elite Basketball Assessment','$75','60 min','Full skills + development assessment'],['Private Basketball Training','$125','60 min','Customized 1-on-1 development'],['Private 4-Pack','$450','4 sessions','Structured private development'],['Private 8-Pack','$800','8 sessions','High-frequency private development'],['Private 12-Pack','$1,050','12 sessions','Longer-term transformation plan'],['Elite Group Basketball','$40','75 min','Handles, scoring, IQ + competition'],['Shooting Lab','$50','75 min','Tracked purposeful shooting reps'],['Pro Experience','$175','90 min','Train at a professional pace with Coach Tae']];
const football=[['Football Performance Assessment','$75','60 min','Speed, movement + position evaluation'],['Private Football Training','$125','60 min','Position-specific 1-on-1 development'],['Private 4-Pack','$450','4 sessions','Structured private development'],['Private 8-Pack','$800','8 sessions','High-frequency private development'],['Private 12-Pack','$1,050','12 sessions','Longer-term transformation plan'],['Football Position Academy','$40','75 min','QB, WR/TE, RB, DB, LB + line tracks'],['Speed + Agility','$40','60 min','Acceleration, COD + sprint mechanics'],['Combine Prep','$75','75 min','40, splits, jumps + testing strategy'],['4-Week Combine Program','$499','8 sessions','Full structured combine preparation']];
const memberships=[['Rookie','$149/mo','4 group sessions','Athlete profile','Progress tracking','Member camp pricing'],['Starter','$249/mo','8 group sessions','Monthly assessment','Performance tracking','Athlete profile'],['Elite','$399/mo','8 group + 2 private','Monthly assessment','Development plan','Film review'],['Pro','$649/mo','8 group + 4 private','Monthly assessment','Film analysis','Recruiting/profile consultation']];
const camps=[['Saturday Skills Camp','$75','2–3 hours'],['Elite One-Day Camp','$149','4–5 hours'],['Two-Day Elite Camp','$249','2 days'],['Three-Day Elite Academy','$349','3 days'],['Pro Basketball Camp','$249','Coach Tae'],['Football Elite Camp','$199','Coach Justin'],['Combine Prep Session','$75','Testing prep'],['Team Training','$350+','Per session']];

const pageData={
'basketball':{label:'BASKETBALL',title:'TRAIN WITH COACH TAE.',copy:'Active international professional basketball athlete. Pro habits, pace, decision-making and detail — translated into development for the next level.',surface:'hardwood',items:basketball,cta:'BOOK BASKETBALL'},
'football':{label:'FOOTBALL',title:'BUILT FOR GAME DAY.',copy:'Coach Justin leads position development, speed, agility, combine preparation and competitive football performance.',surface:'turf',items:football,cta:'BOOK FOOTBALL'},
'programs':{label:'TRAINING PROGRAMS',title:'PICK THE WORK. BUILD THE RESULT.',copy:'Assessments, private development, small groups, position work, shooting, speed, camps and team training.',surface:'hybrid',items:[...basketball.slice(0,2),...football.slice(0,2),['Elite Group Basketball','$40','75 min','Small-group basketball'],['Shooting Lab','$50','75 min','Game-speed shooting'],['Football Position Academy','$40','75 min','Position-specific football'],['Speed + Agility','$40','60 min','Cross-sport performance'],['Combine Prep','$75','75 min','Testing preparation'],['Team Training','$350+','90 min','Program and team development']],cta:'REQUEST TRAINING'},
'memberships':{label:'MEMBERSHIPS',title:'CONSISTENCY BECOMES SEPARATION.',copy:'Recurring athlete development built around training frequency, assessments, film, tracking and priority access.',surface:'light',plans:memberships,cta:'JOIN MEMBER’S ELITE'},
'camps':{label:'CAMPS + COMBINES',title:'THE NEXT STAGE STARTS HERE.',copy:'High-energy development environments for athletes, teams and prospects.',surface:'turf',items:camps,cta:'RESERVE A SPOT'},
'athlete-hq':{label:'ATHLETE HQ',title:'YOUR DEVELOPMENT. VISIBLE.',copy:'A digital athlete profile connecting training history, assessments, performance metrics, recruiting progress and management opportunities.',surface:'light',features:['Training history + attendance','Assessment records','40 / vertical / agility metrics','Shooting + basketball metrics','Trainer notes + goals','Film + recruiting status','Offers + college interest','Management pathway status'],cta:'START YOUR PROFILE'},
'management':{label:'SPORTS MANAGEMENT',title:'BUILD THE ATHLETE ENTERPRISE.',copy:'Member’s Elite goes beyond a traditional agency model. We connect career, brand, media, business, relationships and long-term ownership strategy.',surface:'dark',features:['Athlete Management','Brand Development','Endorsements + Partnerships','Media + Content','Business Development','Events + Experiences','Exclusive + Non-Exclusive Models','Long-Term Legacy Planning'],cta:'APPLY FOR MANAGEMENT'},
'recruiting-nil':{label:'RECRUITING + NIL',title:'TURN PERFORMANCE INTO LEVERAGE.',copy:'Build the profile, film, relationships, brand and opportunity system around the athlete — without confusing training purchase with guaranteed representation.',surface:'turf',features:['Athlete recruiting profile','Highlight + film organization','College targeting support','Coach outreach preparation','NIL education','Personal brand architecture','Partnership readiness','Internal management qualification'],cta:'START THE PATH'},
'coaches':{label:'OUR COACHES',title:'REAL EXPERIENCE. REAL DEVELOPMENT.',copy:'Member’s Elite launches with dedicated basketball and football leadership.',surface:'hybrid',coaches:true,cta:'BOOK A COACH'},
'about':{label:'ABOUT MEMBER’S ELITE',title:'MORE THAN A WORKOUT. MORE THAN A CONTRACT.',copy:'Member’s Elite is an athlete-development and sports-management ecosystem built to train athletes, measure growth, create exposure, develop brands and build long-term value.',surface:'light',features:['Training + performance','Measurement + Athlete HQ','Camps + showcases','Recruiting + NIL support','Sports management','Brand + business development','Network + opportunity','Legacy + ownership'],cta:'BOOK TRAINING'},
'book':{label:'BOOK TRAINING',title:'START YOUR JOURNEY.',copy:'Choose your sport and program. We will confirm coach, location and availability before your session is finalized.',surface:'turf',book:true},
'apply':{label:'MANAGEMENT',title:'BUILD BEYOND THE GAME.',copy:'Tell Member’s Elite what you are building and where you need support.',surface:'dark',apply:true}
};

function ProgramGrid({items=[]}){return <div className="routeGrid">{items.map(([name,price,time,desc])=><article key={name}><span>{time}</span><h3>{name}</h3><strong>{price}</strong><p>{desc}</p><Link href="/book">BOOK →</Link></article>)}</div>}
function FeatureGrid({items=[]}){return <div className="featureGrid">{items.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div>}

export async function generateMetadata({params}){const {slug}=await params;const p=pageData[slug];return p?{title:`${p.label} | Member’s Elite`,description:p.copy}:{}}

export default async function RoutePage({params}){const {slug}=await params;const p=pageData[slug];if(!p)notFound();return <main><SiteNav/>
<section className={'routeHero '+p.surface}><div className="routeTexture"/><div className="routeHeroInner"><span>{p.label}</span><h1>{p.title}</h1><p>{p.copy}</p>{!p.book&&!p.apply&&<Link className="primaryCta" href={slug==='management'?'/apply':'/book'}>{p.cta} →</Link>}</div></section>
{p.book?<section className="routeContent light"><div className="contentHead"><span>TRAINING REQUEST</span><h2>BOOK BASKETBALL OR FOOTBALL.</h2><p>Bookings are requests until coach availability, location, payment and waiver are complete.</p></div><BookingForm/></section>:null}
{p.apply?<InquiryForm/>:null}
{p.items?<section className="routeContent"><div className="contentHead"><span>PROGRAM CATALOG</span><h2>CHOOSE YOUR DEVELOPMENT TRACK.</h2></div><ProgramGrid items={p.items}/></section>:null}
{p.plans?<section className="routeContent"><div className="membershipGrid routePlans">{p.plans.map(([name,price,...benefits],i)=><article className={'membershipCard '+(i===1?'popular':'')} key={name}>{i===1&&<small>MOST POPULAR</small>}<h3>{name}</h3><strong>{price}</strong>{benefits.map(x=><p key={x}>✓ {x}</p>)}<Link href="/book">JOIN →</Link></article>)}</div></section>:null}
{p.features?<section className="routeContent"><div className="contentHead"><span>THE SYSTEM</span><h2>BUILT AROUND THE ATHLETE.</h2></div><FeatureGrid items={p.features}/></section>:null}
{p.coaches?<section className="routeContent"><div className="coachRouteGrid"><article className="hardwoodLite"><span>BASKETBALL</span><h2>COACH TAE</h2><p>Active international professional basketball athlete and elite skills trainer.</p><Link href="/basketball">VIEW BASKETBALL →</Link></article><article className="turfLite"><span>FOOTBALL</span><h2>COACH JUSTIN</h2><p>Football development, position work, speed, agility and combine preparation.</p><Link href="/football">VIEW FOOTBALL →</Link></article></div></section>:null}
{!p.book&&!p.apply&&<section className="routeBottomCta"><span>MEMBER’S ELITE</span><h2>READY TO MOVE?</h2><div><Link className="primaryCta" href="/book">BOOK TRAINING →</Link><Link className="ghostCta" href="/apply">MANAGEMENT →</Link></div></section>}
<SiteFooter/></main>}
