import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteNav,SiteFooter} from '../../components/SiteChrome';
import BookingForm from '../../components/BookingForm';
import InquiryForm from '../../components/InquiryForm';
import AthleteHQClient from '../../components/AthleteHQClient';

const basketball=[['Elite Basketball Assessment','$75','60 min','Baseline skills, movement and development assessment with a program recommendation.'],['Private Basketball Training','$125','60 min','Customized 1-on-1 ball handling, shooting, scoring, footwork and decision-making.'],['Private 4-Pack','$450','4 sessions','Structured private development with continuity.'],['Private 8-Pack','$800','8 sessions','High-frequency private development.'],['Private 12-Pack','$1,050','12 sessions','Longer-term transformation plan.'],['Elite Group Basketball','$40','75 min','Handles, scoring, IQ and live competition.'],['Shooting Lab','$50','75 min','Tracked purposeful game-speed shooting reps.'],['Pro Experience','$175','90 min','Train at professional pace with Coach Tae.']];
const football=[['Football Performance Assessment','$75','60 min','Speed, movement and position evaluation with a development recommendation.'],['Private Football Training','$125','60 min','Position-specific 1-on-1 development.'],['Private 4-Pack','$450','4 sessions','Structured private development.'],['Private 8-Pack','$800','8 sessions','High-frequency private development.'],['Private 12-Pack','$1,050','12 sessions','Longer-term transformation plan.'],['Football Position Academy','$40','75 min','QB, WR/TE, RB, DB, LB and line tracks.'],['Speed + Agility','$40','60 min','Acceleration, change of direction and sprint mechanics.'],['Combine Prep','$75','75 min','40, splits, jumps, agility and testing strategy.'],['4-Week Combine Program','$499','8 sessions','Full structured combine preparation.']];
const memberships=[['Rookie','$149/mo','4 group sessions','Athlete profile','Progress tracking','Member camp pricing'],['Starter','$249/mo','8 group sessions','Monthly assessment','Performance tracking','Athlete profile','Member camp pricing'],['Elite','$399/mo','8 group + 2 private','Monthly assessment','Development plan','Film review','Performance tracking','Priority booking'],['Pro','$649/mo','8 group + 4 private','Monthly performance assessment','Film analysis','Individual development plan','Recruiting/profile consultation','Priority booking','Camp/showcase discounts']];
const camps=[['Saturday Skills Camp','$75','2–3 hours','High-energy skills development and competition.'],['Elite One-Day Camp','$149','4–5 hours','Training, competition and evaluation in one day.'],['Two-Day Elite Camp','$249','2 days','Immersive two-day development.'],['Three-Day Elite Academy','$349','3 days','Three-day intensive academy.'],['Pro Basketball Camp','$199–$299','Coach Tae','Premium basketball camp led by active pro experience.'],['Football Elite Camp','$149–$249','Coach Justin','Position coaching, testing and competition.'],['Combine Prep Session','$75','Testing prep','Testing mechanics and prospect preparation.'],['Team Training','$350+','90 min','Schools, AAU, youth programs and clubs.']];
const ageBands=[['YOUTH DEVELOPMENT','7–10','Fundamentals, movement, confidence and coordination.'],['NEXT LEVEL','11–13','Skill development plus competitive concepts.'],['ELITE PREP','14–18','Varsity, AAU, college and elite-performance preparation.'],['COLLEGE / PRO','18+','College athletes, professionals, overseas players and serious prospects.']];

const pageData={
'basketball':{label:'BASKETBALL',title:'TRAIN WITH COACH TAE.',copy:'Active international professional basketball athlete. Pro habits, pace, decision-making and detail — translated into development for the next level.',surface:'hardwood',items:basketball,cta:'BOOK BASKETBALL',age:true},
'football':{label:'FOOTBALL',title:'BUILT FOR GAME DAY.',copy:'Coach Justin leads position development, speed, agility, combine preparation and competitive football performance.',surface:'turf',items:football,cta:'BOOK FOOTBALL',age:true},
'programs':{label:'TRAINING PROGRAMS',title:'PICK THE WORK. BUILD THE RESULT.',copy:'Assessments, private development, small groups, position work, shooting, speed, camps and team training.',surface:'hybrid',items:[...basketball.slice(0,2),...football.slice(0,2),['Elite Group Basketball','$40','75 min','Small-group basketball.'],['Shooting Lab','$50','75 min','Game-speed shooting.'],['Football Position Academy','$40','75 min','Position-specific football.'],['Speed + Agility','$40','60 min','Cross-sport performance.'],['Combine Prep','$75','75 min','Testing preparation.'],['Team Training','$350+','90 min','Program and team development.']],cta:'REQUEST TRAINING',age:true,team:true},
'memberships':{label:'MEMBERSHIPS',title:'CONSISTENCY BECOMES SEPARATION.',copy:'Recurring athlete development built around training frequency, assessments, film, tracking and priority access.',surface:'light',plans:memberships,cta:'JOIN MEMBER’S ELITE'},
'camps':{label:'CAMPS + COMBINES',title:'THE NEXT STAGE STARTS HERE.',copy:'High-energy development environments for athletes, teams and prospects.',surface:'turf',items:camps,cta:'RESERVE A SPOT'},
'athlete-hq':{label:'ATHLETE HQ',title:'YOUR DEVELOPMENT. VISIBLE.',copy:'A real athlete record connecting training history, assessments, measurable performance, recruiting progress and membership status.',surface:'light',portal:true},
'management':{label:'SPORTS MANAGEMENT',title:'BUILD THE ATHLETE ENTERPRISE.',copy:'Member’s Elite can strengthen the full ecosystem around an athlete: development, brand, media, partnerships, business and long-term legacy planning.',surface:'dark',features:['Athlete Development','Brand Development','Endorsements + Partnerships','Media + Content','Business Development','Events + Experiences','Recruiting Support','Long-Term Legacy Planning'],cta:'APPLY FOR MANAGEMENT',management:true},
'recruiting-nil':{label:'RECRUITING + NIL',title:'TURN PERFORMANCE INTO LEVERAGE.',copy:'Build the athlete profile, film, academic story, relationships, brand and opportunity system without confusing development support with guaranteed placement or representation.',surface:'turf',features:['Athlete recruiting profile','Highlight + film organization','College targeting support','Coach outreach preparation','NIL education','Personal brand architecture','Partnership readiness','Internal management qualification'],cta:'START THE PATH'},
'coaches':{label:'OUR COACHES',title:'REAL EXPERIENCE. REAL DEVELOPMENT.',copy:'Member’s Elite launches with dedicated basketball and football leadership.',surface:'hybrid',coaches:true,cta:'BOOK A COACH'},
'about':{label:'ABOUT MEMBER’S ELITE',title:'MORE THAN A WORKOUT. A HIGHER STANDARD.',copy:'Member’s Elite is an athlete-development and sports-management ecosystem built to train athletes, measure growth, create exposure, develop brands and build long-term value.',surface:'light',features:['Training + performance','Measurement + Athlete HQ','Camps + showcases','Recruiting + NIL support','Sports management','Brand + business development','Network + opportunity','Legacy + ownership'],cta:'BOOK TRAINING',age:true},
'book':{label:'BOOK TRAINING',title:'START YOUR JOURNEY.',copy:'Select the sport, program, athlete, coach/facility preference and schedule request. The request then enters the Member’s Elite operating pipeline.',surface:'turf',book:true},
'apply':{label:'MANAGEMENT',title:'BUILD BEYOND THE GAME.',copy:'Tell Member’s Elite what you are building and where you need support.',surface:'dark',apply:true}
};

function ProgramGrid({items=[]}){return <div className="routeGrid">{items.map(([name,price,time,desc])=><article key={name}><span>{time}</span><h3>{name}</h3><strong>{price}</strong><p>{desc}</p><Link href="/book">BOOK →</Link></article>)}</div>}
function FeatureGrid({items=[]}){return <div className="featureGrid">{items.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div>}
function AgeGrid(){return <section className="routeContent ageSection"><div className="contentHead"><span>DEVELOPMENT DIVISIONS</span><h2>RIGHT WORK. RIGHT STAGE.</h2><p>Every athlete should train inside a development context appropriate to age, competition level and next objective.</p></div><div className="ageGrid">{ageBands.map(([n,a,d])=><article key={n}><span>{a}</span><h3>{n}</h3><p>{d}</p></article>)}</div></section>}

export async function generateMetadata({params}){const {slug}=await params;const p=pageData[slug];return p?{title:`${p.label} | Member’s Elite`,description:p.copy}:{}}

export default async function RoutePage({params}){const {slug}=await params;const p=pageData[slug];if(!p)notFound();return <main><SiteNav/>
<section className={'routeHero '+p.surface}><div className="routeTexture"/><div className="routeHeroInner"><span>{p.label}</span><h1>{p.title}</h1><p>{p.copy}</p>{!p.book&&!p.apply&&!p.portal&&<Link className="primaryCta" href={slug==='management'?'/apply':'/book'}>{p.cta} →</Link>}</div></section>
{p.portal?<AthleteHQClient/>:null}
{p.book?<section className="routeContent light bookingRoute"><div className="contentHead"><span>DEVELOPMENT PIPELINE</span><h2>SPORT → ATHLETE → COACH → SESSION.</h2><p>This is now a structured booking intake, not a generic contact form. Every request is stored as a development record and routed for coach/facility matching.</p></div><BookingForm/></section>:null}
{p.apply?<InquiryForm/>:null}
{p.items?<section className="routeContent"><div className="contentHead"><span>PROGRAM CATALOG</span><h2>CHOOSE YOUR DEVELOPMENT TRACK.</h2></div><ProgramGrid items={p.items}/></section>:null}
{p.plans?<section className="routeContent membershipRoute"><div className="contentHead"><span>RECURRING DEVELOPMENT</span><h2>ASSESS. TRAIN. TRACK. REPEAT.</h2><p>The membership is the long-term engine: training frequency, measurement and progression instead of isolated sessions.</p></div><div className="membershipGrid routePlans">{p.plans.map(([name,price,...benefits],i)=><article className={'membershipCard '+(i===1?'popular':'')} key={name}>{i===1&&<small>MOST POPULAR</small>}<h3>{name}</h3><strong>{price}</strong>{benefits.map(x=><p key={x}>✓ {x}</p>)}<Link href="/book">START WITH AN ASSESSMENT →</Link></article>)}</div></section>:null}
{p.features?<section className="routeContent"><div className="contentHead"><span>THE SYSTEM</span><h2>BUILT AROUND THE ATHLETE.</h2></div><FeatureGrid items={p.features}/>{p.management?<p className="legalNote">Professional contract representation, where offered, is subject to applicable licensing, certification, league/association, state-law and NIL requirements. Training, development, recruiting support and brand services can operate independently.</p>:null}</section>:null}
{p.coaches?<section className="routeContent"><div className="coachRouteGrid"><article className="hardwoodLite"><span>BASKETBALL</span><h2>COACH TAE</h2><p>Active international professional basketball athlete and elite skills trainer.</p><Link href="/basketball">VIEW BASKETBALL →</Link></article><article className="turfLite"><span>FOOTBALL</span><h2>COACH JUSTIN</h2><p>Football development, position work, speed, agility and combine preparation.</p><Link href="/football">VIEW FOOTBALL →</Link></article></div></section>:null}
{p.age?<AgeGrid/>:null}
{p.team?<section className="routeContent teamContracts"><div className="contentHead"><span>TEAM + ORGANIZATION TRAINING</span><h2>BUILD THE WHOLE PROGRAM.</h2></div><div className="contractGrid"><article><b>$350</b><span>SINGLE TEAM SESSION</span></article><article><b>$1,200</b><span>4-SESSION PACKAGE</span></article><article><b>$2,200</b><span>8-SESSION PACKAGE</span></article><article><b>$5,000+</b><span>SEASON DEVELOPMENT CONTRACT</span></article></div></section>:null}
{!p.book&&!p.apply&&!p.portal&&<section className="routeBottomCta"><span>MEMBER’S ELITE</span><h2>READY TO MOVE?</h2><div><Link className="primaryCta" href="/book">BOOK TRAINING →</Link><Link className="ghostCta" href="/athlete-hq">ATHLETE HQ →</Link></div></section>}
<SiteFooter/></main>}
