'use client';
import {useEffect,useState} from 'react';
const URL='https://dzlmtvodpyhetvektfuo.supabase.co';
const KEY='sb_publishable_ekvoOK6QQ05dUZuWgzQfUw_2RgbWPFR';
const apiHeaders=token=>({apikey:KEY,Authorization:`Bearer ${token||KEY}`,'Content-Type':'application/json'});

export default function AthleteHQClient(){
 const [token,setToken]=useState(''),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[data,setData]=useState({metrics:[],assessments:[],sessions:[],reports:[],memberships:[],recruiting:null}),[mode,setMode]=useState('login'),[status,setStatus]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{const t=localStorage.getItem('me_access_token');if(!t){setLoading(false);return}restore(t)},[]);
 async function restore(t){try{const r=await fetch(`${URL}/auth/v1/user`,{headers:apiHeaders(t)});if(!r.ok)throw Error();const u=await r.json();setToken(t);setUser(u);await loadProfile(t)}catch{localStorage.removeItem('me_access_token')}finally{setLoading(false)}}
 async function loadProfile(t){const r=await fetch(`${URL}/rest/v1/members_elite_athletes?select=*&order=created_at.asc`,{headers:apiHeaders(t)});if(!r.ok)return;const list=await r.json();const p=list?.[0];setProfile(p||null);if(!p)return;const [metrics,assessments,sessions,reports,memberships,recruiting]=await Promise.all([
  q(t,`members_elite_performance_metrics?athlete_id=eq.${p.id}&select=*&order=measured_at.desc&limit=12`),q(t,`members_elite_assessments?athlete_id=eq.${p.id}&select=*&order=assessment_date.desc&limit=6`),q(t,`members_elite_training_sessions?athlete_id=eq.${p.id}&select=*&order=starts_at.desc&limit=12`),q(t,`members_elite_trainer_reports?athlete_id=eq.${p.id}&select=*&order=created_at.desc&limit=8`),q(t,`members_elite_membership_enrollments?athlete_id=eq.${p.id}&select=*&order=created_at.desc&limit=4`),q(t,`members_elite_recruiting_profiles?athlete_id=eq.${p.id}&select=*&limit=1`)]);setData({metrics,assessments,sessions,reports,memberships,recruiting:recruiting?.[0]||null});}
 async function authSubmit(e){e.preventDefault();setStatus('WORKING…');const fd=new FormData(e.currentTarget),email=fd.get('email'),password=fd.get('password');try{const endpoint=mode==='login'?'token?grant_type=password':'signup';const r=await fetch(`${URL}/auth/v1/${endpoint}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)throw Error(j.msg||j.message||'Unable to continue');if(!j.access_token){setStatus('CHECK YOUR EMAIL TO CONFIRM THE ACCOUNT, THEN RETURN TO ATHLETE HQ.');return}localStorage.setItem('me_access_token',j.access_token);setToken(j.access_token);setUser(j.user);setStatus('');await loadProfile(j.access_token)}catch(err){setStatus(err.message)}}
 async function createProfile(e){e.preventDefault();setStatus('SAVING PROFILE…');const fd=new FormData(e.currentTarget);const payload={user_id:user.id,full_name:fd.get('full_name'),email:user.email,sport:fd.get('sport'),position:fd.get('position'),school_team:fd.get('school_team'),graduation_year:fd.get('graduation_year')?Number(fd.get('graduation_year')):null,height_inches:fd.get('height_inches')?Number(fd.get('height_inches')):null,weight_lbs:fd.get('weight_lbs')?Number(fd.get('weight_lbs')):null};try{const r=await fetch(`${URL}/rest/v1/members_elite_athletes`,{method:'POST',headers:{...apiHeaders(token),Prefer:'return=representation'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.message||'Unable to save profile');setProfile(j[0]);setStatus('');await loadProfile(token)}catch(err){setStatus(err.message)}}
 function logout(){localStorage.removeItem('me_access_token');setToken('');setUser(null);setProfile(null);setData({metrics:[],assessments:[],sessions:[],reports:[],memberships:[],recruiting:null})}
 if(loading)return <section className="hqPortal"><div className="hqLoading">LOADING ATHLETE HQ…</div></section>;
 if(!user)return <section className="hqPortal authPortal"><div className="hqAuthIntro"><span>MEMBER’S ELITE ATHLETE ID</span><h2>YOUR DEVELOPMENT.<br/>ONE RECORD.</h2><p>Training history, assessments, metrics, film, recruiting progress and membership status live together here.</p><div className="hqPillRow"><b>PERFORMANCE</b><b>TRAINING</b><b>RECRUITING</b><b>MANAGEMENT PATHWAY</b></div></div><form className="hqAuthCard" onSubmit={authSubmit}><span>{mode==='login'?'ATHLETE LOGIN':'CREATE ATHLETE ACCESS'}</span><h3>{mode==='login'?'WELCOME BACK.':'START YOUR ATHLETE ID.'}</h3><label><span>EMAIL</span><input name="email" type="email" required autoComplete="email"/></label><label><span>PASSWORD</span><input name="password" type="password" required minLength="6" autoComplete={mode==='login'?'current-password':'new-password'}/></label><button className="primaryCta">{mode==='login'?'ENTER ATHLETE HQ →':'CREATE ACCOUNT →'}</button>{status&&<p className="hqStatus">{status}</p>}<button className="textButton" type="button" onClick={()=>{setMode(mode==='login'?'signup':'login');setStatus('')}}>{mode==='login'?'New athlete? Create access':'Already have access? Sign in'}</button></form></section>;
 if(!profile)return <section className="hqPortal profileSetup"><div className="hqAuthIntro"><span>PROFILE ACTIVATION</span><h2>BUILD YOUR<br/>ATHLETE ID.</h2><p>This becomes the permanent development record connected to your training, assessments and recruiting pathway.</p></div><form className="hqAuthCard" onSubmit={createProfile}><div className="formGrid"><label><span>FULL NAME</span><input name="full_name" required/></label><label><span>SPORT</span><select name="sport"><option value="basketball">Basketball</option><option value="football">Football</option><option value="multi">Multi-Sport</option></select></label><label><span>POSITION</span><input name="position"/></label><label><span>SCHOOL / TEAM</span><input name="school_team"/></label><label><span>GRADUATION YEAR</span><input name="graduation_year" type="number" min="2026" max="2045"/></label><label><span>HEIGHT (INCHES)</span><input name="height_inches" type="number" min="36" max="96"/></label><label><span>WEIGHT (LBS)</span><input name="weight_lbs" type="number" min="50" max="600"/></label></div><button className="primaryCta">ACTIVATE PROFILE →</button>{status&&<p className="hqStatus">{status}</p>}</form></section>;
 const metricMap=Object.fromEntries(data.metrics.map(m=>[m.metric_key,m]));
 return <section className="athleteDashboard"><aside className="hqSide"><div className="hqMonogram">ME</div><nav>{['OVERVIEW','PERFORMANCE','TRAINING','ASSESSMENTS','RECRUITING','MEMBERSHIP'].map((x,i)=><a href={'#hq-'+i} key={x}>{x}</a>)}</nav><button onClick={logout}>SIGN OUT</button></aside><div className="hqMain">
  <header className="hqTop"><div><span>MEMBER’S ELITE ATHLETE HQ</span><h2>{profile.full_name}</h2><p>{[profile.graduation_year&&`Class of ${profile.graduation_year}`,profile.position,profile.school_team].filter(Boolean).join(' · ')}</p></div><div className="athleteStatus"><span>DEVELOPMENT STATUS</span><b>{profile.recruiting_status?.replaceAll('_',' ').toUpperCase()}</b></div></header>
  <div className="identityStats" id="hq-0"><Stat label="HEIGHT" value={profile.height_inches?feet(profile.height_inches):'—'}/><Stat label="WEIGHT" value={profile.weight_lbs?`${profile.weight_lbs} lbs`:'—'}/><Stat label="GPA" value={profile.gpa||'—'}/><Stat label="SPORT" value={profile.sport?.toUpperCase()}/></div>
  <section className="hqSection" id="hq-1"><div className="hqSectionHead"><span>PERFORMANCE</span><h3>WHAT GETS MEASURED GETS BETTER.</h3></div><div className="metricCards">{[['shooting_pct','SHOOTING %'],['vertical','VERTICAL'],['forty_yard','40 YARD'],['agility','AGILITY']].map(([k,l])=><Stat key={k} label={l} value={metricMap[k]?.metric_text||metricMap[k]?.metric_value||'NO DATA'}/>)}</div>{!data.metrics.length&&<Empty text="Your first assessment will begin populating measurable performance here."/>}</section>
  <section className="hqSection" id="hq-2"><div className="hqSectionHead"><span>TRAINING HISTORY</span><h3>EVERY SESSION SHOULD MOVE THE RECORD.</h3></div><div className="hqList">{data.sessions.map(s=><article key={s.id}><b>{s.program_slug.replaceAll('-',' ').toUpperCase()}</b><span>{s.starts_at?new Date(s.starts_at).toLocaleDateString():'DATE PENDING'}</span><small>{s.attendance_status.toUpperCase()}</small></article>)}</div>{!data.sessions.length&&<Empty text="Booked and completed Member’s Elite sessions will appear here."/>}</section>
  <section className="hqSection" id="hq-3"><div className="hqSectionHead"><span>ASSESSMENTS + COACH REPORTS</span><h3>THE PLAN AFTER THE WORK.</h3></div><div className="reportGrid">{data.assessments.map(a=><article key={a.id}><span>{a.assessment_date}</span><h4>{a.assessment_type}</h4><b>{a.overall_score?`${a.overall_score} / 100`:'ASSESSED'}</b><p>{a.priorities||a.notes||'Development notes recorded.'}</p></article>)}{data.reports.map(r=><article key={r.id}><span>TRAINER REPORT</span><h4>{r.trainer_slug.replaceAll('-',' ')}</h4><p>{r.session_summary||r.wins||'Session report recorded.'}</p><small>{r.next_program_recommendation||''}</small></article>)}</div>{!data.assessments.length&&!data.reports.length&&<Empty text="Assessments and post-session trainer reports will live here—not in scattered texts or notes."/>}</section>
  <section className="hqSection splitHQ" id="hq-4"><div><div className="hqSectionHead"><span>RECRUITING + NIL</span><h3>TURN DEVELOPMENT INTO LEVERAGE.</h3></div><p>{data.recruiting?.academic_summary||'Film, academic data, targets, offers and NIL readiness become part of the athlete record as the pathway develops.'}</p><div className="pathwayTag">{data.recruiting?.nil_readiness_status?.replaceAll('_',' ').toUpperCase()||'NIL PATHWAY NOT STARTED'}</div></div><div id="hq-5"><div className="hqSectionHead"><span>MEMBERSHIP</span><h3>CONSISTENCY BECOMES SEPARATION.</h3></div>{data.memberships.length?<div className="pathwayTag">{data.memberships[0].plan_slug.toUpperCase()} · {data.memberships[0].status.toUpperCase()}</div>:<><p>No active membership is linked to this athlete yet.</p><a className="primaryCta" href="/memberships">VIEW MEMBERSHIPS →</a></>}</div></section>
 </div></section>
}
async function q(token,path){try{const r=await fetch(`${URL}/rest/v1/${path}`,{headers:apiHeaders(token)});return r.ok?await r.json():[]}catch{return []}}
function Stat({label,value}){return <article><span>{label}</span><b>{value}</b></article>}
function Empty({text}){return <div className="hqEmpty">{text}</div>}
function feet(n){const x=Number(n);return `${Math.floor(x/12)}’${x%12}”`}
