'use client';
import {useEffect,useMemo,useState} from 'react';

const URL='https://dzlmtvodpyhetvektfuo.supabase.co';
const KEY='sb_publishable_ekvoOK6QQ05dUZuWgzQfUw_2RgbWPFR';
const headers={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'};
const fallbackPrograms=[
 {slug:'basketball-assessment',sport:'basketball',name:'Basketball Assessment',price_label:'$75',duration_minutes:60,trainer_slug:'coach-tae'},
 {slug:'basketball-private',sport:'basketball',name:'Private Basketball Training',price_label:'$125',duration_minutes:60,trainer_slug:'coach-tae'},
 {slug:'elite-group-basketball',sport:'basketball',name:'Elite Group Basketball',price_label:'$40',duration_minutes:75,trainer_slug:'coach-tae'},
 {slug:'shooting-lab',sport:'basketball',name:'Shooting Lab',price_label:'$50',duration_minutes:75,trainer_slug:'coach-tae'},
 {slug:'pro-experience',sport:'basketball',name:'Pro Experience with Coach Tae',price_label:'$175',duration_minutes:90,trainer_slug:'coach-tae'},
 {slug:'football-assessment',sport:'football',name:'Football Performance Assessment',price_label:'$75',duration_minutes:60,trainer_slug:'coach-justin'},
 {slug:'football-private',sport:'football',name:'Private Football Training',price_label:'$125',duration_minutes:60,trainer_slug:'coach-justin'},
 {slug:'football-position-academy',sport:'football',name:'Football Position Academy',price_label:'$40',duration_minutes:75,trainer_slug:'coach-justin'},
 {slug:'combine-prep',sport:'football',name:'Combine Prep',price_label:'$75',duration_minutes:75,trainer_slug:'coach-justin'},
 {slug:'combine-4-week',sport:'football',name:'4-Week Combine Program',price_label:'$499',duration_minutes:75,trainer_slug:'coach-justin'},
 {slug:'speed-agility',sport:'all',name:'Speed + Agility',price_label:'$40',duration_minutes:60,trainer_slug:null},
 {slug:'team-training',sport:'all',name:'Team Training',price_label:'$350+',duration_minutes:90,trainer_slug:null}
];
const empty={sport:'basketball',program_slug:'basketball-assessment',athlete_name:'',guardian_name:'',email:'',phone:'',age:'',graduation_year:'',level_team:'',position:'',goals:'',trainer_slug:'coach-tae',location_slug:'atlanta-basketball-assigned',preferred_date:'',preferred_time:'',waiver_accepted:false,waiver_name:'',membership_interest:'',source:'memberseliteatl.com'};

export default function BookingForm(){
 const [programs,setPrograms]=useState(fallbackPrograms),[locations,setLocations]=useState([]),[f,setF]=useState(empty),[step,setStep]=useState(1),[state,setState]=useState('idle'),[msg,setMsg]=useState('');
 useEffect(()=>{Promise.all([
   fetch(`${URL}/rest/v1/members_elite_programs?is_active=eq.true&select=slug,sport,category,name,description,duration_minutes,price_label,trainer_slug,eligibility,capacity&order=sort_order.asc`,{headers}).then(r=>r.ok?r.json():[]),
   fetch(`${URL}/rest/v1/members_elite_locations?is_active=eq.true&select=slug,name,sport,instructions&order=name.asc`,{headers}).then(r=>r.ok?r.json():[])
 ]).then(([p,l])=>{if(p?.length)setPrograms(p);if(l?.length)setLocations(l)}).catch(()=>{})},[]);
 const available=useMemo(()=>programs.filter(p=>p.sport===f.sport||p.sport==='all'),[programs,f.sport]);
 const selected=programs.find(p=>p.slug===f.program_slug)||available[0];
 const locs=locations.filter(l=>l.sport===f.sport||l.sport==='all');
 const set=k=>e=>setF(v=>({...v,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
 function chooseSport(s){const list=programs.filter(p=>p.sport===s||p.sport==='all');setF(v=>({...v,sport:s,program_slug:list[0]?.slug||'',trainer_slug:s==='basketball'?'coach-tae':'coach-justin',location_slug:s==='basketball'?'atlanta-basketball-assigned':'atlanta-football-assigned'}));}
 function next(e){e?.preventDefault();setMsg('');setStep(x=>Math.min(4,x+1));window.scrollTo({top:Math.max(0,document.querySelector('.bookingShell')?.offsetTop-100),behavior:'smooth'});}
 function back(){setMsg('');setStep(x=>Math.max(1,x-1));}
 async function submit(e){e.preventDefault();if(!f.waiver_accepted){setMsg('The waiver acknowledgement is required to submit this request.');return}setState('loading');setMsg('');const id=crypto.randomUUID();try{
   const booking={...f,id,age:f.age?Number(f.age):null,graduation_year:f.graduation_year?Number(f.graduation_year):null,trainer_slug:selected?.trainer_slug||f.trainer_slug,waiver_accepted:true,status:'new',payment_status:'not_started',ghl_sync_status:'pending'};
   const r=await fetch(`${URL}/rest/v1/members_elite_booking_requests`,{method:'POST',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify(booking)});if(!r.ok)throw new Error('booking');
   const w=await fetch(`${URL}/rest/v1/members_elite_waivers`,{method:'POST',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({booking_request_id:id,athlete_name:f.athlete_name,signer_name:f.waiver_name||f.guardian_name||f.athlete_name,signer_email:f.email,accepted:true,accepted_at:new Date().toISOString()})});if(!w.ok)throw new Error('waiver');
   await fetch(`${URL}/rest/v1/members_elite_inquiries`,{method:'POST',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({inquiry_type:'training_booking',full_name:f.athlete_name,email:f.email,phone:f.phone,sport:f.sport,level_team:f.level_team,message:`Program: ${selected?.name||f.program_slug}\nPreferred: ${f.preferred_date} ${f.preferred_time}\nPosition: ${f.position}\nGoals: ${f.goals}`,source:'memberseliteatl.com',status:'new'})}).catch(()=>{});
   setState('success');setStep(5);setMsg(`Request ${id.slice(0,8).toUpperCase()} received. We’ll match the coach and facility, then send the payment/confirmation step.`);
 }catch(err){setState('error');setMsg('Your request could not be saved. Please try again or contact Member’s Elite directly.')}}
 return <div className="bookingShell">
   <div className="bookingSteps">{['PROGRAM','ATHLETE','SCHEDULE','REVIEW'].map((x,i)=><div className={(step===i+1?'active ':'')+(step>i+1?'done':'')} key={x}><b>{i+1}</b><span>{x}</span></div>)}</div>
   {step===1&&<form className="bookingPanel" onSubmit={next}><div className="bookingLead"><span>01 / SELECT YOUR TRACK</span><h3>WHAT ARE WE BUILDING?</h3><p>Start with the sport and development product. Assessments are the strongest entry point for a new athlete.</p></div><div className="sportToggle"><button type="button" className={f.sport==='basketball'?'active':''} onClick={()=>chooseSport('basketball')}>BASKETBALL</button><button type="button" className={f.sport==='football'?'active':''} onClick={()=>chooseSport('football')}>FOOTBALL</button></div><div className="programChoiceGrid">{available.map(p=><label className={f.program_slug===p.slug?'selected':''} key={p.slug}><input type="radio" name="program" value={p.slug} checked={f.program_slug===p.slug} onChange={e=>setF(v=>({...v,program_slug:e.target.value,trainer_slug:p.trainer_slug||v.trainer_slug}))}/><small>{p.duration_minutes?`${p.duration_minutes} MIN`:'PROGRAM'}</small><strong>{p.name}</strong><b>{p.price_label}</b><p>{p.description}</p></label>)}</div><div className="bookingActions"><button className="primaryCta">CONTINUE TO ATHLETE →</button></div></form>}
   {step===2&&<form className="bookingPanel" onSubmit={next}><div className="bookingLead"><span>02 / ATHLETE PROFILE</span><h3>WHO ARE WE DEVELOPING?</h3><p>This information becomes the beginning of the athlete’s Member’s Elite development record.</p></div><div className="formGrid"><Field label="ATHLETE NAME *" value={f.athlete_name} onChange={set('athlete_name')} required/><Field label="PARENT / GUARDIAN" value={f.guardian_name} onChange={set('guardian_name')}/><Field label="EMAIL *" type="email" value={f.email} onChange={set('email')} required/><Field label="PHONE *" type="tel" value={f.phone} onChange={set('phone')} required/><Field label="AGE" type="number" min="6" max="80" value={f.age} onChange={set('age')}/><Field label="GRADUATION YEAR" type="number" min="2026" max="2045" value={f.graduation_year} onChange={set('graduation_year')}/><Field label="LEVEL / TEAM" value={f.level_team} onChange={set('level_team')} placeholder="Varsity / AAU / College / Pro"/><Field label="POSITION" value={f.position} onChange={set('position')} placeholder="Guard / WR / DB / etc."/><label className="wide"><span>DEVELOPMENT GOALS</span><textarea rows="5" value={f.goals} onChange={set('goals')} placeholder="What needs to improve? What is the next level?"/></label></div><div className="bookingActions"><button type="button" className="ghostCta" onClick={back}>← BACK</button><button className="primaryCta">CONTINUE TO SCHEDULE →</button></div></form>}
   {step===3&&<form className="bookingPanel" onSubmit={next}><div className="bookingLead"><span>03 / COACH + FACILITY + TIME</span><h3>BUILD THE SESSION.</h3><p>Coach and facility assignments are validated before the session becomes final.</p></div><div className="scheduleSummary"><article><span>PROGRAM</span><b>{selected?.name}</b><strong>{selected?.price_label}</strong></article><article><span>TRAINER</span><b>{f.sport==='basketball'?'Coach Tae':'Coach Justin'}</b><strong>{f.sport.toUpperCase()}</strong></article></div><div className="formGrid"><label><span>LOCATION</span><select value={f.location_slug} onChange={set('location_slug')}>{(locs.length?locs:[{slug:f.location_slug,name:'Atlanta — Assigned Facility'}]).map(l=><option value={l.slug} key={l.slug}>{l.name}</option>)}</select></label><Field label="PREFERRED DATE *" type="date" value={f.preferred_date} onChange={set('preferred_date')} required/><label><span>PREFERRED WINDOW *</span><select required value={f.preferred_time} onChange={set('preferred_time')}><option value="">Select</option><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Flexible</option></select></label><label><span>MEMBERSHIP INTEREST</span><select value={f.membership_interest} onChange={set('membership_interest')}><option value="">Not yet</option><option value="rookie">Rookie — $149/mo</option><option value="starter">Starter — $249/mo</option><option value="elite">Elite — $399/mo</option><option value="pro">Pro — $649/mo</option></select></label></div><div className="bookingActions"><button type="button" className="ghostCta" onClick={back}>← BACK</button><button className="primaryCta">REVIEW REQUEST →</button></div></form>}
   {step===4&&<form className="bookingPanel" onSubmit={submit}><div className="bookingLead"><span>04 / REVIEW + WAIVER</span><h3>LOCK THE REQUEST.</h3><p>Review the athlete track, acknowledge the participation waiver, and send the request into Member’s Elite operations.</p></div><div className="reviewGrid"><article><span>ATHLETE</span><b>{f.athlete_name}</b><p>{f.level_team||'Development athlete'} · {f.position||'Position TBD'}</p></article><article><span>PROGRAM</span><b>{selected?.name}</b><p>{selected?.price_label} · {selected?.duration_minutes?selected.duration_minutes+' min':'Program'}</p></article><article><span>COACH</span><b>{f.sport==='basketball'?'Coach Tae':'Coach Justin'}</b><p>{f.sport}</p></article><article><span>REQUESTED</span><b>{f.preferred_date||'Date TBD'}</b><p>{f.preferred_time||'Time flexible'}</p></article></div><div className="waiverBox"><h4>PARTICIPATION ACKNOWLEDGEMENT</h4><p>I understand that athletic training involves physical activity and that submitting this form is a request, not a confirmed session. Final coach/facility availability, payment and any required detailed release documentation must be completed before participation.</p><Field label="SIGNER NAME *" value={f.waiver_name} onChange={set('waiver_name')} required/><label className="checkLine"><input type="checkbox" checked={f.waiver_accepted} onChange={set('waiver_accepted')}/><span>I have read and accept this acknowledgement.</span></label></div>{msg&&<p className={'formMessage '+state}>{msg}</p>}<div className="bookingActions"><button type="button" className="ghostCta" onClick={back}>← BACK</button><button className="primaryCta" disabled={state==='loading'}>{state==='loading'?'SAVING…':'SUBMIT REQUEST →'}</button></div><small>Payment is not charged on this request screen. A confirmed slot must be matched before the payment/confirmation step is released.</small></form>}
   {step===5&&<section className="bookingSuccess"><span>REQUEST RECEIVED</span><h3>THE DEVELOPMENT PIPELINE STARTS NOW.</h3><p>{msg}</p><div className="successPath"><b>REQUEST</b><i>→</i><b>COACH + FACILITY MATCH</b><i>→</i><b>PAYMENT</b><i>→</i><b>SESSION</b><i>→</i><b>TRAINER REPORT</b><i>→</i><b>REBOOK / MEMBERSHIP</b></div><a className="primaryCta" href="/memberships">EXPLORE MEMBERSHIPS →</a></section>}
 </div>
}

function Field({label,...props}){return <label><span>{label}</span><input {...props}/></label>}
