const engines=[['01','ATHLETIC CAREER','Protect performance, maximize career value, and plan beyond the next contract.'],['02','BRAND','Build identity, influence, leverage, and market value.'],['03','MEDIA + CULTURE','Turn visibility into story, audience, content, and cultural relevance.'],['04','BUSINESS','Create products, investments, partnerships, and ownership while the lights are on.'],['05','LEGACY','Build a platform that outlives the game and creates generational impact.']];
const services=[['ATHLETE MANAGEMENT','Career planning','Introductions','Scheduling'],['BRAND DEVELOPMENT','Identity systems','Web + social','Campaign strategy'],['ENDORSEMENTS + PARTNERSHIPS','Brand deals','Ambassadorships','Licensing'],['MEDIA + CONTENT','Photoshoots','Digital series','Podcasts'],['EVENTS + EXPERIENCES','Camps','Clinics','Celebrity events'],['BUSINESS DEVELOPMENT','Products','Investments','Joint ventures']];
const exclusive=['Integrated management','Brand strategy','Partnership sourcing','Content + appearances','Business development','Long-term planning'];
const non=['Works alongside existing teams','Brand + sponsorship support','Events + camps','Photoshoots + marketing','Business introductions','Opportunity expansion'];

export function Mindset(){return <section className="mind"><div className="wrap two"><div className="kicker">01 / THE MINDSET</div><div><h2>THE TRADITIONAL SPORTS MANAGEMENT MODEL <em>IS TOO SMALL.</em></h2><p className="lead">Today’s athlete can be a competitor, brand, business owner, media personality, and long-term enterprise — all at once.</p><blockquote>“ WHAT CAN WE BUILD <strong>WHILE YOU’RE STILL PLAYING?</strong> ”</blockquote><div className="rail">{['ATHLETIC CAREER','BRAND','MEDIA','BUSINESS','COMMUNITY','LEGACY'].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div></div></section>}

export function Model(){return <section className="model" id="model"><div className="wrap"><Head n="02 / THE MODEL" title={<>ONE ATHLETE.<br/><em>MULTIPLE GROWTH ENGINES.</em></>} copy="Members Elite becomes the strategic command center around the athlete, connecting career, visibility, relationships, and ownership."/><div className="orbit"><div className="rings"/><div className="core"><span className="me">M<span>E</span></span><b>ATHLETE<br/>COMMAND CENTER</b></div>{engines.map((e,i)=><article className={'engine e'+(i+1)} key={e[1]}><b>{e[0]}</b><h3>{e[1]}</h3><p>{e[2]}</p></article>)}</div><div className="bigline">NOTHING OPERATES IN ISOLATION.</div></div></section>}

export function Services(){return <section className="services" id="services"><div className="wrap"><Head n="03 / THE ECOSYSTEM" title={<>THE ATHLETE<br/><em>SERVICES ECOSYSTEM.</em></>} copy="One athlete. Multiple revenue and growth channels."/><div className="cards">{services.map((s,i)=><article key={s[0]}><b className="num">0{i+1}</b><span className="ico">{['A','B','E','M','X','↗'][i]}</span><h3>{s[0]}</h3><p>{s.slice(1).join(' · ')}</p></article>)}</div><div className="value">REVENUE <i>+</i> EQUITY <i>+</i> OWNERSHIP <i>+</i> RELATIONSHIPS</div></div></section>}

export function Management(){return <section className="manage"><div className="wrap manageGrid"><div><div className="kicker">04 / MANAGEMENT</div><h2><em>EXCLUSIVE</em> +<br/>NON-EXCLUSIVE.</h2><p className="lead">Different athletes require different relationships. We can lead the entire ecosystem or strengthen the team already in place.</p><div className="power">WE DO NOT HAVE TO REPLACE AN ATHLETE’S TEAM.<strong>WE CAN MAKE THAT TEAM MORE POWERFUL.</strong></div></div><div className="rels"><Rel title="EXCLUSIVE ATHLETES" list={exclusive} gold/><Rel title="NON-EXCLUSIVE ATHLETES" list={non}/></div></div></section>}
function Rel({title,list,gold}){return <article className={'rel '+(gold?'rg':'')}><h3>{title}</h3>{list.map(x=><p key={x}><b>{gold?'◆':'◇'}</b>{x}</p>)}</article>}

export function BrandNetwork(){return <><section className="brand"><div className="brandVisual"><div className="stadium"><span>24</span></div></div><div className="brandCopy"><div className="kicker">05 / BRAND CAPITAL</div><h2>BUILD THE BRAND<br/><em>WHILE THE LIGHTS ARE ON.</em></h2><p className="lead">Athletic performance creates attention. Brand strategy converts attention into value.</p><div className="pillars"><p><b>01</b><span><strong>BRAND ARCHITECTURE</strong>Story, identity, audience, positioning.</span></p><p><b>02</b><span><strong>VISUAL DEVELOPMENT</strong>Photography, campaigns, websites, merchandise.</span></p><p><b>03</b><span><strong>COMMERCIAL POSITIONING</strong>Partnership-ready athlete profiles.</span></p></div><blockquote>Every athlete should become a <strong>marketable intellectual property asset.</strong></blockquote></div></section><section className="network" id="network"><div className="wrap"><Head n="06 / NETWORK EFFECT" title={<>ATHLETES BUILDING<br/><em>WITH ATHLETES.</em></>} copy="Structured collaboration during active careers creates more deal flow, ownership opportunities, and a stronger platform for every athlete in the ecosystem."/><div className="networkGrid"><div className="net"><div className="netCore"><span className="me">M<span>E</span></span></div>{[1,2,3,4,5,6,7,8].map(i=><i className={'n'+i} key={i}/>)}</div><div className="ops">{['Joint ventures','Shared investments','Co-hosted camps','Cross-sport collaborations','Mentorship + deal flow'].map((x,i)=><p key={x}><b>0{i+1}</b><span>{x}</span><i>↗</i></p>)}<article><small>THE MEMBERS ELITE</small><strong>NETWORK EFFECT</strong><span>Every quality athlete added to the ecosystem increases value for every other athlete.</span></article></div></div><div className="collective">INDIVIDUAL SUCCESS BECOMES <strong>COLLECTIVE OPPORTUNITY.</strong></div></div></section></>}

export function PipelineVision(){const steps=['YOUTH','HIGH SCHOOL','COLLEGE','PROFESSIONAL','BUSINESS','MENTORSHIP','OWNERSHIP'];const assets=['NAME','STORY','NETWORK','AUDIENCE','INFLUENCE','CAPITAL','OWNERSHIP'];return <><section className="pipeline" id="pipeline"><div className="wrap"><Head n="07 / DEVELOPMENT" title={<>PROFESSIONAL FIRST.<br/><em>YOUTH PIPELINE NEXT.</em></>} copy="We launch with professional football and basketball, then build the next generation through camps, skill development, mentorship, NIL education, and entrepreneurship."/><div className="focus"><article><small>LAUNCH FOCUS</small><strong>FOOTBALL</strong><p>NFL · pro development · select collegiate relationships</p></article><article><small>LAUNCH FOCUS</small><strong>BASKETBALL</strong><p>NBA · international basketball · former professionals</p></article></div><div className="steps">{steps.map((x,i)=><span key={x}><b>0{i+1}</b>{x}{i<6&&<i>→</i>}</span>)}</div></div></section><section className="vision"><div className="wrap visionIn"><div><div className="kicker">08 / THE VISION</div><h2>BUILDING THE<br/><em>ATHLETE ENTERPRISE.</em></h2><p className="lead">Your greatest asset is bigger than a contract.</p><div className="assetStack">{assets.map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div><div className="visionQuote"><p>Traditional agencies manage athletic careers.</p><strong>MEMBERS ELITE HELPS BUILD ATHLETE ENTERPRISES.</strong><b>PLAY ELITE. LIVE ELITE. BUILD ELITE.</b></div></div></section></>}

function Head({n,title,copy}){return <div className="head"><div><div className="kicker">{n}</div><h2>{title}</h2></div><p>{copy}</p></div>}
